---
- hosts: all
  become: true
  tasks:
    - name: update apt
      apt: update_cache=yes

    - name: install depends
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - iperf
        - iptables
        - iptables-persistent

    - sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: iptables rules
      notify: reload iptables
      copy:
        dest: /etc/iptables/rules.v4
        src: iptables-sc-rules

    - name: network config
      notify: restart network
      copy:
        dest: /etc/network/interfaces
        content: |
          auto lo
          iface lo inet loopback

          auto eth0
          iface eth0 inet dhcp
                post-up ip route del default dev eth0 || true

          auto eth1
          iface eth1 inet static
                address 33.33.1.2
                netmask 255.255.255.0
                gateway 33.33.1.1

  handlers:
    - name: restart network
      service: name=networking state=restarted

    - name: reload iptables
      command: "iptables-restore /etc/iptables/rules.v4"
