---
- hosts: all
  become: true
  tasks:
    - name: update apt
      apt: update_cache=yes

    - name: install depends
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - iperf
        - iptables
        - iptables-persistent

    - sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: iptables rules
      notify: reload iptables
      copy:
        dest: /etc/iptables/rules.v4
        src: iptables-r-rules

  handlers:
    - name: reload iptables
      command: "iptables-restore /etc/iptables/rules.v4"
